### ISSUE TITLE
相对路径的svg文件编译问题

### ISSUE THREAD

**Issue by akira-cn** [Jinjiang/vue-simple-compiler#2]
sfc代码片段：

```html
<template>
  <header>
    <img alt="Vue logo" class="logo" src="./assets/logo.svg" width="125" height="125" />

    <div class="wrapper">
      <HelloWorld msg="You did it!" />
    </div>
  </header>

  <main>
    <TheWelcome />
  </main>
</template>
```

编译出来的结果：

```
import _imports_0 from './assets/logo.svg'


const _withScopeId = n => (_pushScopeId("data-v-24601251"),n=n(),_popScopeId(),n)
const _hoisted_1 = /*#__PURE__*/ _withScopeId(() => /*#__PURE__*/_createElementVNode("img", {
  alt: "Vue logo",
  class: "logo",
  src: _imports_0,
  width: "125",
  height: "125"
}, null, -1))
const _hoisted_2 = { class: "wrapper" }
```

这样还得处理一下 import svg。

而Vite代码编译的结果直接是：

```js
const _hoisted_1 = /*#__PURE__*/ _withScopeId(() => /*#__PURE__*/_createElementVNode("img", {
  alt: "Vue logo",
  class: "logo",
  src: "/src/assets/logo.svg",
  width: "125",
  height: "125"
}, null, -1 /* HOISTED */))
```

**Comment by Jinjiang** [comment]
是的，这个 compiler 在设计之初的用意就是把 vue 相关的编译跟 bundler 以及其它资源的 compiler 解耦，我简单试了一下把编译结果直接放到 vite 里是可以工作的。大概是这样：
https://github.com/Jinjiang/reproductions/tree/vue-simple-compiler-with-svg-20230821

**Comment by akira-cn** [comment]
> 是的，这个 compiler 在设计之初的用意就是把 vue 相关的编译跟 bundler 以及其它资源的 compiler 解耦，我简单试了一下把编译结果直接放到 vite 里是可以工作的。大概是这样： https://github.com/Jinjiang/reproductions/tree/vue-simple-compiler-with-svg-20230821

但我如果在非vite的开发环境里使用，就得再用其他工具编译一次了，因为我想在 AirCode 里面使用，这个是模板：https://github.com/AirCodeLabs/aircode/tree/main/examples/vue-template

我只能把svg文件上传到CDN。

**Comment by akira-cn** [comment]
@Jinjiang  能否提供一个options，这样我就可以选择不编译svg资源文件，这样compiler编译出来的js代码就是合法的es modules，可以不用再转一次直接 import 进来 debug.

**Comment by Jinjiang** [comment]
这个 import 其实是 vue-compiler 内部做的，我这里并没有做特殊处理，另外完全合法的 es module compiler 理论上是不存在的，比如 `<style module>` 的情况是无论如何也无法转换成纯 es modules 的。从这个 compiler 到实际使用我觉得难免要再加一层编译，并且这一层编译和 vue 本身是可以完全解耦的。

如果 vue-compiler 内部有类似的选项我可以从 options 里透出这个肯定没有问题，这个我可以再多看一眼

谢谢

**Comment by Jinjiang** [comment]
@akira-cn 久等了，我找到了一个可以配置的 compiler option 实现你想要的编译结果。具体看这个 case test：
https://github.com/Jinjiang/vue-simple-compiler/blob/3419173145d774c9c79272c3db6549e30cbad5a3/test/compiler.spec.ts#L704
新版 v0.0.6 刚发布，可以试一下
https://www.npmjs.com/package/vue-simple-compiler/v/0.0.6
